---
  gather_facts: false
  hosts: all
  tasks: 
    win_feature: 
        include_application_development: true
        include_common_http_futures: true
        include_health_and_diagnostics: true
        include_management_tools: true
        include_performance: true
        include_security: true
        include_sub_features: true
        name: Web-Server
        restart: true
        state: present
    win_file: 
        path: "C:\\WEB\\TEMP"
        state: directory

    win_acl: 
        path: "C:\\WEB\\TEMP"
        rights: fullcontrol
        type: allow
        user: everyone

    win_iis_webapppool: 
        managedPipelineMode: Integrated
        managedRuntimeVersion: v4.0
        name: DefaultAppPool
        state: Started
        attributes: 
            idleTimeout: 0
            queueLength: 65535
            rapidFailProtextion: false
            regularTimeInterval: 0
            startMode: AlwaysRunning
