---
# This playbook installs and enables IIS on Windows hosts

- name: Install IIS
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
        include_application_development : yes
        include_security: yes
        include_performance: yes
        include_health_and_diagnostics: yes
        include_common_http_futures: yes
     
- name: Create directory structure
  win_file: 
    path: "C:\\WEB\\TEMP"
    state: directory
    
- name: Give rights to folder
  win_acl: 
    path: "C:\\WEB\\TEMP"
    rights: fullcontrol
    type: allow
    user: everyone
    
- name: Return information about an existing application pool
  win_iis_webapppool:
    managedPipelineMode: Integrated
    managedRuntimeVersion: v4.0
    name: DefaultAppPool
    attributes: 
      idleTimeout: 0
      queueLength: 65535
      rapidFailProtextion: false
      regularTimeInterval: 0
      startMode: AlwaysRunning
      state: Started

